// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzoxzazxuvgidhyjbmzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6b3h6YXp4dXZnaWRoeWpibXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODE5OTgsImV4cCI6MjA2MTM1Nzk5OH0.sZNRp7p0BGrBlZ9zGqx7BwudDFmZfamotzmEMqLRD1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);